repos:
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
    - id: flake8
      language_version: python3.10

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.4.1
    hooks:
    - id: mypy
      language_version: python3.10
      additional_dependencies: [types-simplejson,pydantic]

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
    - id: isort
      language_version: python3.10
      args: ["--profile", "black", "--filter-files"]

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    - id: black
      language_version: python3.10
      args: [--config=pyproject.toml]
  # - repo: https://github.com/pycqa/isort
  #   rev: 5.6.4
  #   hooks:
  #     - id: isort
  #       args: ["--profile", "black", "--filter-files"]
 
