dataset:
  _target_: src.dataset.GoogleMachineDataset
  name: google_machine
  raw_path: ./raw_data/m_1.csv
machine_id: 1
'y': cpu
base_path: /lcrc/project/FastBayes/rayandrew/sched-cl
out_path: /lcrc/project/FastBayes/rayandrew/sched-cl/out/google_machine/m_1_cpu_naive
filename: data/google_machine/m_1/m_1_125-5/m_1_cpu.csv
drift:
  window_size: 125
  threshold: 5
cuda: 0
sequential: false
seq_len: 5
n_labels: 10
lr: 0.001
batch_size: 32
epoch: 8
n_workers: 4
strategy: naive
tolerance: 1
univariate: false
seed: 3003
