dataset:
  _target_: src.dataset.AlibabaMachineDataset
  type: machine
  raw_path: /lcrc/project/FastBayes/rayandrew/machine_usage/m_881.csv
machine_id: 881
'y': disk
base_path: /lcrc/project/FastBayes/rayandrew/sched-cl
out_path: /lcrc/project/FastBayes/rayandrew/sched-cl/out/m_881_disk
filename: data/machine/m_881/m_881_75-300/m_881_disk.csv
drift:
  window_size: 75
  threshold: 300
cuda: 0
sequential: true
seq_len: 5
n_labels: 10
lr: 0.001
batch_size: 32
epoch: 8
n_workers: 4
strategy: naive
tolerance: 1
univariate: false
