scenario:
  offline_classification_no_retrain:
    num_split: 8 
  offline_classification_retrain_chunks:
    num_split: 8 
  offline_classification_retrain_chunks_from_scratch:
    num_split: 8 
  offline_classification_retrain_chunks_naive:
    num_split: 8 
  offline_classification_retrain_chunks_gss_greedy:
    num_split: 8
