defaults:
  # - dataset: alibaba_machine
  - dataset: google_machine
  - _self_
  # - train/model: resnet
  # - train/optimizer: sgd

machine_id: 5
y: cpu
base_path: /Users/rayandrew/Research/argonne-cl/sched-cl # needed for SLURM
out_path: ${base_path}/out/${dataset.name}/m_${machine_id}_${y}_${strategy}
filename: data/${dataset.name}/m_${machine_id}/m_${machine_id}_${drift.window_size}-${drift.threshold}/m_${machine_id}_${y}.csv
drift:
  window_size: 75
  threshold: 300
cuda: 0
sequential: false
seq_len: 5
n_labels: 10
lr: 0.001
batch_size: 32
epoch: 8
n_workers: 4
strategy: ewc
tolerance: 1
univariate: false
seed: 3003
